workflows:
  feature-branch-workflow:
    name: Feature Branch CI/CD
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'feature/*'
          include: true
      cancel_previous_builds: true
    
    environment:
      groups:
        - firebase_credentials
        - github_credentials
        # - ios_credentials  # Comentado temporalmente - solo probando Android
      vars:
        PACKAGE_NAME: "com.example.cicdexample"
        FLUTTER_VERSION: "3.9.0"
      flutter: stable
      # xcode: latest  # Comentado temporalmente - solo probando Android
      # cocoapods: default  # Comentado temporalmente - solo probando Android
    
    scripts:
      - name: Setup Firebase configuration files
        script: |
          # Crear el archivo google-services.json desde variable de entorno
          if [ -n "$GOOGLE_SERVICES_JSON" ]; then
            echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
            echo "✅ google-services.json creado desde variable de entorno"
          elif [ -n "$GOOGLE_SERVICE_JSON" ]; then
            echo "$GOOGLE_SERVICE_JSON" > android/app/google-services.json
            echo "✅ google-services.json creado desde variable de entorno (fallback)"
          else
            echo "❌ ERROR: Variables GOOGLE_SERVICES_JSON o GOOGLE_SERVICE_JSON no están configuradas"
            exit 1
          fi
          
          # Crear directorios para productFlavors si no existen
          mkdir -p android/app/src/production/release
          mkdir -p android/app/src/release
          mkdir -p android/app/src/production
          mkdir -p android/app/src/productionRelease
          
          # Copiar el archivo a todas las ubicaciones que Gradle busca
          cp android/app/google-services.json android/app/src/production/release/google-services.json
          cp android/app/google-services.json android/app/src/release/google-services.json
          cp android/app/google-services.json android/app/src/production/google-services.json
          cp android/app/google-services.json android/app/src/productionRelease/google-services.json
          
          echo "✅ Archivos google-services.json copiados a todas las ubicaciones necesarias"
          echo "📁 Verificando archivos creados:"
          ls -la android/app/google-services.json
          ls -la android/app/src/production/release/google-services.json 2>/dev/null || echo "⚠️  No se pudo verificar todas las ubicaciones"
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Run tests
        script: |
          flutter test
      
      - name: Increment build number
        script: |
          # Leer el build number actual del pubspec.yaml
          CURRENT_BUILD=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f2)
          NEW_BUILD=$((CURRENT_BUILD + 1))
          VERSION_NAME=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          
          # Actualizar el pubspec.yaml con el nuevo build number
          sed -i.bak "s/version: .*/version: $VERSION_NAME+$NEW_BUILD/" pubspec.yaml
          
          echo "Build number incrementado: $CURRENT_BUILD -> $NEW_BUILD"
          echo "NEW_BUILD_NUMBER=$NEW_BUILD" >> $CM_ENV
      
      - name: Build Android APK
        script: |
          flutter build apk --release --build-number=$NEW_BUILD_NUMBER
      
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release --build-number=$NEW_BUILD_NUMBER
      
      # Comentado temporalmente - solo probando Android
      # - name: Build iOS IPA
      #   script: |
      #     flutter build ipa --release --build-number=$NEW_BUILD_NUMBER
      
      - name: Create GitHub Pull Request
        script: |
          # Verificar que GITHUB_TOKEN está configurado
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "⚠️  GITHUB_TOKEN no está configurado, saltando creación de PR"
            exit 0
          fi
          
          # Instalar GitHub CLI si no está disponible
          if ! command -v gh &> /dev/null; then
            brew install gh
          fi
          
          # Configurar GitHub CLI para usar el token directamente (sin autenticación interactiva)
          # GitHub CLI reconoce automáticamente GH_TOKEN sin necesidad de gh auth login
          export GH_TOKEN="$GITHUB_TOKEN"
          
          # Obtener información de la rama
          BRANCH_NAME=${CM_BRANCH}
          BASE_BRANCH="develop"
          FEATURE_NAME=${BRANCH_NAME#feature/}
          
          # Verificar si el PR ya existe
          EXISTING_PR=$(gh pr list --repo $CM_REPO_SLUG --head $BRANCH_NAME --base $BASE_BRANCH --json number --jq '.[0].number' 2>/dev/null || echo "")
          
          if [ -n "$EXISTING_PR" ]; then
            echo "✅ PR #$EXISTING_PR ya existe para esta rama"
          else
            # Crear el PR
            gh pr create \
              --repo $CM_REPO_SLUG \
              --base $BASE_BRANCH \
              --head $BRANCH_NAME \
              --title "QA Review: $FEATURE_NAME" \
              --body "🚀 **Build automático generado por Codemagic**
            
            **Rama:** \`$BRANCH_NAME\`
            **Build Number:** $NEW_BUILD_NUMBER
            **Plataformas:** Android
            
            La aplicación está disponible en Firebase App Distribution para testing de QA.
            
            ---
            _Este PR fue creado automáticamente por el workflow de CI/CD_" \
              && echo "✅ PR creado exitosamente" \
              || echo "⚠️  No se pudo crear el PR (puede que ya exista o haya un error)"
          fi
    
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      # - build/ios/ipa/*.ipa  # Comentado temporalmente - solo probando Android
      - flutter_drive.log
    
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: $FIREBASE_APP_ID_ANDROID
          groups:
            - qa-testers
          artifact_type: apk
        # Comentado temporalmente - solo probando Android
        # ios:
        #   app_id: $FIREBASE_APP_ID_IOS
        #   groups:
        #     - qa-testers
      
      email:
        recipients:
          - horacioduca23@gmail.com
        notify:
          success: true
          failure: true

